version: "3.1"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mariadb:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    amqp:
        image: rabbitmq:3.7.6-management
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
