version: "3.1"

services:
    app:
        build: .
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./backend:/var/www/backend
            - ./configs:/var/www/configs
            - ./frontend:/var/www/frontend
        environment:
            MYSQL_SERVER: db
            MYSQL_DATABASE: test
            MYSQL_PORT: 3306
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: root
            AMQP_HOST: amqp://root:root@amqp

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mariadb:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    amqp:
        image: rabbitmq:3.7.6-management
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
